export const nodes = [
  { id: 'r00', size: 1, color: 'lightGrey' },
  { id: 'r10', size: 2, color: 'lightGrey' },
  { id: 'r11', size: 8, color: 'lightGrey' },
  { id: 'r12', size: 8, color: 'lightGrey' },
  { id: 'r13', size: 8, color: 'lightGrey' },
  { id: 'r14', size: 8, color: 'lightGrey' },
  { id: 'r20', size: 2, color: 'lightGrey' },
  { id: 'r21', size: 4, color: 'lightGrey' },
  { id: 'r22', size: 4, color: 'lightGrey' },
  { id: 'r23', size: 4, color: 'lightGrey' },
  { id: 'r24', size: 4, color: 'lightGrey' },
  { id: 'r25', size: 4, color: 'lightGrey' },
  { id: 'r26', size: 4, color: 'lightGrey' },
  { id: 'r27', size: 4, color: 'lightGrey' },
  { id: 'r28', size: 4, color: 'lightGrey' },
  { id: 'r30', size: 2, color: 'lightGrey' },
  { id: 'r40', size: 2, color: 'lightGrey' },
]

export const links = [
  { source: 'r00', target: 'r10', color: 'white' },
  { source: 'r00', target: 'r20', color: 'white' },
  { source: 'r00', target: 'r30', color: 'white' },
  { source: 'r00', target: 'r40', color: 'white' },
  { source: 'r10', target: 'r11', color: 'white' },
  { source: 'r10', target: 'r12', color: 'white' },
  { source: 'r10', target: 'r13', color: 'white' },
  { source: 'r10', target: 'r14', color: 'white' },
  { source: 'r20', target: 'r21', color: 'white' },
  { source: 'r20', target: 'r22', color: 'white' },
  { source: 'r20', target: 'r23', color: 'white' },
  { source: 'r20', target: 'r24', color: 'white' },
  { source: 'r20', target: 'r25', color: 'white' },
  { source: 'r20', target: 'r26', color: 'white' },
  { source: 'r20', target: 'r27', color: 'white' },
  { source: 'r20', target: 'r28', color: 'white' },
]
